#include "Menu_Error.h"
#include "ERC240128FS.h"
#include "Functions.h"
#include "UART_App.h"
#include "Text.h"
#include "Buzzer.h"

const unsigned char ENG_Title_ErrorUnknown[] = {5,'E','r','r','o','r'};
const unsigned char ENG_Description_ErrorUnknown[] = {15,'S','e','e',' ','u','s','e','r',' ','m','a','n','u','a','l'};

// Error list generated by Sprog Generator using Errors.csv (check Fonts and Icons folder)
const unsigned char ENG_Title_E001[] = {6,'E','E','P','R','O','M'};
const unsigned char ENG_Title_E002[] = {6,'E','E','P','R','O','M'};
const unsigned char ENG_Title_E003[] = {12,'H','i','g','h',' ','V','o','l','t','a','g','e'};
const unsigned char ENG_Title_E004[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E005[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E006[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E007[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E008[] = {13,'B','r','o','k','e','n',' ','S','e','n','s','o','r'};
const unsigned char ENG_Title_E009[] = {13,'B','r','o','k','e','n',' ','S','e','n','s','o','r'};
const unsigned char ENG_Title_E010[] = {11,'E','f','f','i','c','i','e','n','c','y',' '};
const unsigned char ENG_Title_E011[] = {11,'I','O',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E012[] = {11,'I','O',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E013[] = {11,'I','O',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E014[] = {11,'I','O',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E020[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E022[] = {7,'C','h','a','r','g','e','r'};
const unsigned char ENG_Title_E023[] = {7,'C','h','a','r','g','e','r'};
const unsigned char ENG_Title_E030[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E031[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E032[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E033[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E034[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E035[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E036[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E037[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E038[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E039[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E040[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E041[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E042[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E043[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E044[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E045[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E046[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E047[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E048[] = {11,'C','a','l','i','b','r','a','t','i','o','n'};
const unsigned char ENG_Title_E050[] = {13,'E','m','p','t','y',' ','B','a','t','t','e','r','y'};
const unsigned char ENG_Title_E051[] = {13,'E','m','p','t','y',' ','B','a','t','t','e','r','y'};
const unsigned char ENG_Title_E052[] = {11,'L','o','w',' ','B','a','t','t','e','r','y'};
const unsigned char ENG_Title_E053[] = {13,'E','m','p','t','y',' ','B','a','t','t','e','r','y'};
const unsigned char ENG_Title_E054[] = {9,'B','a','l','a','n','c','i','n','g'};
const unsigned char ENG_Title_E055[] = {9,'B','a','l','a','n','c','i','n','g'};
const unsigned char ENG_Title_E056[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E057[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E058[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E059[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E060[] = {13,'E','m','p','t','y',' ','B','a','t','t','e','r','y'};
const unsigned char ENG_Title_E061[] = {25,'B','a','t','t','e','r','y',' ','D','i','s','c','h','a','r','g','e',' ','C','u','r','r','e','n','t'};
const unsigned char ENG_Title_E062[] = {22,'B','a','t','t','e','r','y',' ','C','h','a','r','g','e',' ','C','u','r','r','e','n','t'};
const unsigned char ENG_Title_E070[] = {5,'S','o','l','a','r'};
const unsigned char ENG_Title_E071[] = {5,'S','o','l','a','r'};
const unsigned char ENG_Title_E072[] = {5,'S','o','l','a','r'};
const unsigned char ENG_Title_E073[] = {10,'S','o','l','a','r',' ','F','u','s','e'};
const unsigned char ENG_Title_E074[] = {5,'S','o','l','a','r'};
const unsigned char ENG_Title_E075[] = {18,'S','o','l','a','r',' ','S','e','l','f',' ','P','r','o','t','e','c','t'};
const unsigned char ENG_Title_E088[] = {19,'1','2',' ','V','D','C',' ','O','u','t',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E090[] = {12,'L','o','w',' ','D','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E091[] = {13,'H','i','g','h',' ','D','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E092[] = {17,'D','C',' ','I','n','p','u','t',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E093[] = {16,'D','C',' ','I','n','p','u','t',' ','F','a','i','l','u','r','e'};
const unsigned char ENG_Title_E094[] = {16,'1','2',' ','V','D','C',' ','O','u','t',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E095[] = {16,'1','2',' ','V','D','C',' ','O','u','t',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E096[] = {21,'1','2',' ','V','D','C',' ','O','u','t',' ','O','v','e','r','c','h','a','r','g','e'};
const unsigned char ENG_Title_E097[] = {19,'1','2',' ','V','D','C',' ','O','u','t',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E098[] = {19,'D','C',' ','I','n','p','u','t',' ','F','u','s','e',' ','B','l','o','w','n'};
const unsigned char ENG_Title_E099[] = {25,'D','C','-','D','C',' ','t','o',' ','B','a','t','t','.',' ','F','u','s','e',' ','B','l','o','w','n'};
const unsigned char ENG_Title_E101[] = {9,'A','C',' ','O','f','f','s','e','t'};
const unsigned char ENG_Title_E102[] = {9,'D','C',' ','O','f','f','s','e','t'};
const unsigned char ENG_Title_E105[] = {12,'H','i','g','h',' ','V','o','l','t','a','g','e'};
const unsigned char ENG_Title_E120[] = {16,'D','C',' ','I','n','p','u','t',' ','F','a','i','l','u','r','e'};
const unsigned char ENG_Title_E121[] = {11,'C','A','N',' ','F','a','i','l','u','r','e'};
const unsigned char ENG_Title_E122[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E123[] = {11,'T','e','m','p','e','r','a','t','u','r','e'};
const unsigned char ENG_Title_E124[] = {13,'H','i','g','h',' ','D','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E125[] = {13,'H','i','g','h',' ','D','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E126[] = {17,'D','C',' ','I','n','p','u','t',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E127[] = {17,'D','C',' ','I','n','p','u','t',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E130[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E131[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E132[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E133[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E135[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E136[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E137[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E138[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E139[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E140[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E141[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E142[] = {12,'P','o','w','e','r',' ','S','u','p','p','l','y'};
const unsigned char ENG_Title_E150[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E151[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E152[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E153[] = {10,'P','E','/','N',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E154[] = {10,'P','E','/','N',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E155[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E157[] = {16,'I','n','v','e','r','t','e','r',' ','C','u','t','-','O','f','f'};
const unsigned char ENG_Title_E200[] = {15,'2','3','0',' ','V','A','C',' ','I','n',' ','P','e','a','k'};
const unsigned char ENG_Title_E201[] = {15,'2','3','0',' ','V','A','C',' ','I','n',' ','P','e','a','k'};
const unsigned char ENG_Title_E202[] = {12,'H','i','g','h',' ','V','o','l','t','a','g','e'};
const unsigned char ENG_Title_E203[] = {16,'2','3','0',' ','V','A','C',' ','O','v','e','r','l','o','a','d'};
const unsigned char ENG_Title_E204[] = {14,'T','r','a','n','s','f','e','r',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E205[] = {14,'T','r','a','n','s','f','e','r',' ','R','e','l','a','y'};
const unsigned char ENG_Title_E206[] = {14,'2','3','0',' ','V','A','C',' ','I','n',' ','L','o','w'};
const unsigned char ENG_Title_E207[] = {15,'2','3','0',' ','V','A','C',' ','I','n',' ','H','i','g','h'};
const unsigned char ENG_Title_E208[] = {8,'A','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E220[] = {15,'S','y','s','t','e','m',' ','A','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E221[] = {16,'S','y','s','t','e','m',' ','A','C',' ','O','u','t','p','u','t'};
const unsigned char ENG_Title_E222[] = {15,'S','y','s','t','e','m',' ','D','C',' ','I','n','p','u','t'};
const unsigned char ENG_Title_E223[] = {13,'C','o','m','m','u','n','i','c','a','t','i','o','n'};
const unsigned char ENG_Title_E240[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E241[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E242[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E243[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E244[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E245[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E246[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Title_E247[] = {13,'S','y','s','t','e','m',' ','L','o','c','k','e','d'};
const unsigned char ENG_Description_E001[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E002[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E003[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E004[] = {88,'U','n','i','t',' ','i','s',' ','g','e','t','t','i','n','g',' ','t','o','o',' ','c','o','l','d','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','w','a','r','m',' ','u','p',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','h','i','g','h','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E005[] = {80,'U','n','i','t',' ','i','s',' ','t','o','o',' ','c','o','l','d','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','w','a','r','m',' ','u','p',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','h','i','g','h','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E006[] = {90,'U','n','i','t',' ','i','s',' ','g','e','t','t','i','n','g',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E007[] = {82,'U','n','i','t',' ','i','s',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E008[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E009[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E010[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E011[] = {150,'D','i','s','c','o','n','n','e','c','t',' ','I','O',' ','(','R','E','M','O','T','E',')',' ','c','o','n','n','e','c','t','o','r',' ','a','n','d',' ','c','h','e','c','k',' ','f','o','r',' ','c','o','n','n','e','c','t','o','r',' ','o','r',' ','c','a','b','l','e',' ','d','a','m','a','g','e','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E012[] = {148,'D','i','s','c','o','n','n','e','c','t',' ','I','O',' ','(','D','A','T','A',')',' ','c','o','n','n','e','c','t','o','r',' ','a','n','d',' ','c','h','e','c','k',' ','f','o','r',' ','c','o','n','n','e','c','t','o','r',' ','o','r',' ','c','a','b','l','e',' ','d','a','m','a','g','e','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E013[] = {149,'D','i','s','c','o','n','n','e','c','t',' ','I','O',' ','(','F','R','O','N','T',')',' ','c','o','n','n','e','c','t','o','r',' ','a','n','d',' ','c','h','e','c','k',' ','f','o','r',' ','c','o','n','n','e','c','t','o','r',' ','o','r',' ','c','a','b','l','e',' ','d','a','m','a','g','e','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E014[] = {146,'D','i','s','c','o','n','n','e','c','t',' ','I','O',' ','(','C','2',')',' ','c','o','n','n','e','c','t','o','r',' ','a','n','d',' ','c','h','e','c','k',' ','f','o','r',' ','c','o','n','n','e','c','t','o','r',' ','o','r',' ','c','a','b','l','e',' ','d','a','m','a','g','e','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E020[] = {135,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E022[] = {135,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E023[] = {144,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','c','o','n','n','e','c','t','i','o','n','s',' ','a','n','d',' ','r','e','c','o','n','n','e','c','t',' ','t','o',' ','c','o','n','t','i','n','u','e',' ','c','h','a','r','g','i','n','g','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E030[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E031[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E032[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E033[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E034[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E035[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E036[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E037[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E038[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E039[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E040[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E041[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E042[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E043[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E044[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E045[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E046[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E047[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E048[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E050[] = {62,'B','a','t','t','e','r','y',' ','i','s',' ','d','e','e','p','-','d','i','s','c','h','a','r','g','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E051[] = {34,'B','a','t','t','e','r','y',' ','i','s',' ','e','m','p','t','y','.',' ','C','h','a','r','g','e',' ','t','h','e',' ','u','n','i','t','.'};
const unsigned char ENG_Description_E052[] = {32,'B','a','t','t','e','r','y',' ','i','s',' ','l','o','w','.',' ','C','h','a','r','g','e',' ','t','h','e',' ','u','n','i','t','.'};
const unsigned char ENG_Description_E053[] = {34,'B','a','t','t','e','r','y',' ','i','s',' ','e','m','p','t','y','.',' ','C','h','a','r','g','e',' ','t','h','e',' ','u','n','i','t','.'};
const unsigned char ENG_Description_E054[] = {95,'C','e','l','l',' ','b','a','l','a','n','c','i','n','g',' ','i','n',' ','p','r','o','g','r','e','s','s','.',' ','I','f',' ','w','a','r','n','i','n','g',' ','r','e','m','a','i','n','s',' ','a','f','t','e','r',' ','2','4',' ','h','r','s',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E055[] = {95,'C','e','l','l',' ','b','a','l','a','n','c','i','n','g',' ','i','n',' ','p','r','o','g','r','e','s','s','.',' ','I','f',' ','f','a','i','l','u','r','e',' ','r','e','m','a','i','n','s',' ','a','f','t','e','r',' ','2','4',' ','h','r','s',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E056[] = {88,'U','n','i','t',' ','i','s',' ','g','e','t','t','i','n','g',' ','t','o','o',' ','c','o','l','d','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','w','a','r','m',' ','u','p',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','h','i','g','h','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E057[] = {80,'U','n','i','t',' ','i','s',' ','t','o','o',' ','c','o','l','d','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','w','a','r','m',' ','u','p',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','h','i','g','h','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E058[] = {90,'U','n','i','t',' ','i','s',' ','g','e','t','t','i','n','g',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E059[] = {82,'U','n','i','t',' ','i','s',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E060[] = {34,'B','a','t','t','e','r','y',' ','i','s',' ','e','m','p','t','y','.',' ','C','h','a','r','g','e',' ','t','h','e',' ','u','n','i','t','.'};
const unsigned char ENG_Description_E061[] = {163,'B','a','t','t','e','r','y',' ','i','s',' ','b','e','i','n','g',' ','d','i','s','c','h','a','r','g','e','d',' ','w','i','t','h',' ','t','o','o',' ','h','i','g','h',' ','c','u','r','r','e','n','t','.',' ','R','e','m','o','v','e',' ','a','n','y',' ','2','3','0',' ','V','A','C',' ','a','n','d',' ','1','2',' ','V','D','C',' ','l','o','a','d','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E062[] = {172,'B','a','t','t','e','r','y',' ','i','s',' ','b','e','i','n','g',' ','c','h','a','r','g','e','d',' ','w','i','t','h',' ','t','o','o',' ','h','i','g','h',' ','c','u','r','r','e','n','t','.',' ',' ','D','i','s','c','o','n','n','e','c','t',' ','a','l','l',' ','c','h','a','r','g','e',' ','s','o','u','r','c','e','s',' ','(','S','o','l','a','r',',',' ','D','C',',',' ','A','C',')','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E070[] = {84,'C','h','e','c','k',' ','f','o','r',' ','c','o','r','r','e','c','t',' ','s','o','l','a','r',' ','i','n','s','t','a','l','l','a','t','i','o','n',' ','a','n','d',' ','a',' ','v','o','l','t','a','g','e',' ','o','f',' ','m','a','x','i','m','u','m',' ','5','0',' ','V',' ','f','r','o','m',' ','s','o','l','a','r',' ','p','a','n','e','l','.'};
const unsigned char ENG_Description_E071[] = {70,'C','h','e','c','k',' ','f','o','r',' ','c','o','r','r','e','c','t',' ','s','o','l','a','r',' ','i','n','s','t','a','l','l','a','t','i','o','n',' ','a','n','d',' ','m','a','x',' ','c','u','r','r','e','n','t',' ','f','r','o','m',' ','s','o','l','a','r',' ','p','a','n','e','l','.'};
const unsigned char ENG_Description_E072[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E073[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E074[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E075[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E088[] = {56,'1','2',' ','V','D','C',' ','O','u','t','p','u','t',' ','o','v','e','r','l','o','a','d','e','d','.',' ','R','e','m','o','v','e',' ','l','o','a','d',' ','t','o',' ','a','v','o','i','d',' ','s','h','u','t','d','o','w','n','.'};
const unsigned char ENG_Description_E090[] = {69,'D','C',' ','I','n','p','u','t',' ','v','o','l','t','a','g','e',' ','t','o','o',' ','l','o','w',' ','f','o','r',' ','c','h','a','r','g','i','n','g','.',' ','C','h','e','c','k',' ','v','e','h','i','c','l','e',' ','b','a','t','t','e','r','y',' ','v','o','l','t','a','g','e','.'};
const unsigned char ENG_Description_E091[] = {70,'D','C',' ','I','n','p','u','t',' ','v','o','l','t','a','g','e',' ','t','o','o',' ','h','i','g','h',' ','f','o','r',' ','c','h','a','r','g','i','n','g','.',' ','C','h','e','c','k',' ','v','e','h','i','c','l','e',' ','b','a','t','t','e','r','y',' ','v','o','l','t','a','g','e','.'};
const unsigned char ENG_Description_E092[] = {55,'D','C',' ','I','n','p','u','t',' ','o','v','e','r','l','o','a','d','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E093[] = {146,'U','n','a','b','l','e',' ','t','o',' ','c','h','a','r','g','e',' ','f','r','o','m',' ','v','e','h','i','c','l','e',',',' ','c','h','e','c','k',' ','i','n','s','t','a','l','l','a','t','i','o','n',' ','t','o',' ','v','e','h','i','c','l','e',' ','b','a','t','t','e','r','y','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E094[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E095[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E096[] = {66,'1','2',' ','V','D','C',' ','o','u','t','p','u','t',' ','c','h','a','r','g','e',' ','c','u','r','r','e','n','t',' ','t','o','o',' ','h','i','g','h','.',' ','C','h','e','c','k',' ','v','e','h','i','c','l','e',' ','i','n','s','t','a','l','l','a','t','i','o','n','.'};
const unsigned char ENG_Description_E097[] = {129,'R','e','m','o','v','e',' ','1','2',' ','V','D','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E098[] = {72,'T','h','e',' ','i','n','t','e','r','n','a','l',' ','D','C',' ','i','n','p','u','t',' ','f','u','s','e',' ','h','a','s',' ','b','l','o','w','n','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E099[] = {90,'T','h','e',' ','i','n','t','e','r','n','a','l',' ','D','C','-','D','C',' ','c','o','n','v','e','r','t','e','r',' ','t','o',' ','b','a','t','t','e','r','y',' ','f','u','s','e',' ','h','a','s',' ','b','l','o','w','n','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E101[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E102[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E105[] = {130,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E120[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E121[] = {94,'C','h','e','c','k',' ','C','A','N',' ','c','a','b','l','e','s','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E122[] = {90,'U','n','i','t',' ','i','s',' ','g','e','t','t','i','n','g',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E123[] = {82,'U','n','i','t',' ','i','s',' ','t','o','o',' ','h','o','t','.',' ','A','l','l','o','w',' ','i','t',' ','t','o',' ','c','o','o','l',' ','d','o','w','n',' ','o','r',' ','p','l','a','c','e',' ','i','t',' ','i','n',' ','a',' ','l','o','w','e','r',' ','a','m','b','i','e','n','t',' ','t','e','m','p','e','r','a','t','u','r','e','.'};
const unsigned char ENG_Description_E124[] = {71,'D','C',' ','I','n','p','u','t',' ','v','o','l','t','a','g','e',' ','t','o','o',' ','h','i','g','h',' ','f','o','r',' ','c','h','a','r','g','i','n','g','.',' ','C','h','e','c','k',' ','t','h','e',' ','v','e','h','i','c','l','e',' ','i','n','s','t','a','l','l','a','t','i','o','n','.'};
const unsigned char ENG_Description_E125[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E126[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E127[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E130[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E131[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E132[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E133[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E135[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E136[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E137[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E138[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E139[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E140[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E141[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E142[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E150[] = {130,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E151[] = {130,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E152[] = {130,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E153[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E154[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E155[] = {138,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','C','L','E','A','R',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E157[] = {63,'B','a','t','t','e','r','y',' ','S','O','C',' ','b','e','l','o','w',' ','c','u','t','-','o','f','f',' ','l','i','m','i','t','.',' ','C','h','a','r','g','e',' ','u','n','i','t',' ','o','r',' ','d','e','c','r','e','a','s','e',' ','l','i','m','i','t','.'};
const unsigned char ENG_Description_E200[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E201[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E202[] = {106,'P','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E203[] = {130,'R','e','m','o','v','e',' ','2','3','0',' ','V','A','C',' ','l','o','a','d',' ','a','n','d',' ','p','r','e','s','s',' ','<',' ','O','K',' ','>',' ','t','o',' ','r','e','s','t','a','r','t',' ','u','n','i','t','.',' ','I','f',' ','a',' ','r','e','s','t','a','r','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E204[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E205[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E206[] = {177,'2','3','0',' ','V','A','C',' ','I','N',' ','v','o','l','t','a','g','e',' ','t','o','o',' ','l','o','w','.',' ','C','h','e','c','k',' ','s','u','p','p','l','y',' ','c','a','b','l','e','s',',',' ','r','e','m','o','v','e',' ','e','x','t','e','n','s','i','o','n',' ','c','o','r','d',' ','o','r',' ','t','r','y',' ','a','n','o','t','h','e','r',' ','o','u','t','l','e','t',' ','s','o','c','k','e','t','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E207[] = {48,'2','3','0',' ','V','A','C',' ','I','N',' ','v','o','l','t','a','g','e',' ','t','o','o',' ','h','i','g','h','.',' ','C','h','e','c','k',' ','m','a','i','n','s',' ','s','u','p','p','l','y','.'};
const unsigned char ENG_Description_E208[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E220[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E221[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E222[] = {34,'C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E223[] = {94,'C','h','e','c','k',' ','C','A','N',' ','c','a','b','l','e','s','.',' ','I','f',' ','t','h','a','t',' ','d','o','e','s',' ','n','o','t',' ','r','e','m','o','v','e',' ','t','h','e',' ','f','a','i','l','u','r','e',',',' ','t','h','e','n',' ','c','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E240[] = {76,'C','e','l','l',' ','v','o','l','t','a','g','e',' ','c','r','i','t','i','c','a','l','l','y',' ','l','o','w',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E241[] = {77,'C','e','l','l',' ','v','o','l','t','a','g','e',' ','c','r','i','t','i','c','a','l','l','y',' ','h','i','g','h',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E242[] = {79,'B','a','t','t','e','r','y',' ','v','o','l','t','a','g','e',' ','c','r','i','t','i','c','a','l','l','y',' ','l','o','w',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E243[] = {80,'B','a','t','t','e','r','y',' ','v','o','l','t','a','g','e',' ','c','r','i','t','i','c','a','l','l','y',' ','h','i','g','h',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E244[] = {75,'T','e','m','p','e','r','a','t','u','r','e',' ','c','r','i','t','i','c','a','l','l','y',' ','l','o','w',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E245[] = {76,'T','e','m','p','e','r','a','t','u','r','e',' ','c','r','i','t','i','c','a','l','l','y',' ','h','i','g','h',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E246[] = {79,'C','h','a','r','g','e',' ','c','u','r','r','e','n','t',' ','c','r','i','t','i','c','a','l','l','y',' ','h','i','g','h',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};
const unsigned char ENG_Description_E247[] = {82,'D','i','s','c','h','a','r','g','e',' ','c','u','r','r','e','n','t',' ','c','r','i','t','i','c','a','l','l','y',' ','h','i','g','h',',',' ','u','n','i','t',' ','l','o','c','k','e','d','.',' ','C','o','n','t','a','c','t',' ','y','o','u','r',' ','r','e','t','a','i','l','e','r',' ','f','o','r',' ','s','u','p','p','o','r','t','.'};


const Error_Constants ErrorList[] = 
{
    [0]     = {.ErrorNumber = 0,    .ErrorLevel = FL_OK,                .PopLevel = HIDE,   .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [1]     = {.ErrorNumber = 1,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E001,            .Title = ENG_Title_E001},
    [2]     = {.ErrorNumber = 2,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E002,            .Title = ENG_Title_E002},
    [3]     = {.ErrorNumber = 3,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E003,            .Title = ENG_Title_E003},
    [4]     = {.ErrorNumber = 4,    .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E004,            .Title = ENG_Title_E004},
    [5]     = {.ErrorNumber = 5,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,   .Description = ENG_Description_E005,            .Title = ENG_Title_E005},
    [6]     = {.ErrorNumber = 6,    .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E006,            .Title = ENG_Title_E006},
    [7]     = {.ErrorNumber = 7,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,   .Description = ENG_Description_E007,            .Title = ENG_Title_E007},
    [8]     = {.ErrorNumber = 8,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = KEEP,   .Description = ENG_Description_E008,            .Title = ENG_Title_E008},
    [9]     = {.ErrorNumber = 9,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = KEEP,   .Description = ENG_Description_E009,            .Title = ENG_Title_E009},
    [10]    = {.ErrorNumber = 10,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E010,            .Title = ENG_Title_E010}, //REMOVED AT MBN
    [11]    = {.ErrorNumber = 11,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E011,            .Title = ENG_Title_E011}, //ADDED
    [12]    = {.ErrorNumber = 12,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E012,            .Title = ENG_Title_E012}, //ADDED
    [13]    = {.ErrorNumber = 13,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E013,            .Title = ENG_Title_E013}, //ADDED
    [14]    = {.ErrorNumber = 14,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E014,            .Title = ENG_Title_E014}, //ADDED
    [15]    = {.ErrorNumber = 15,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [16]    = {.ErrorNumber = 16,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [17]    = {.ErrorNumber = 17,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [18]    = {.ErrorNumber = 18,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [19]    = {.ErrorNumber = 19,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [20]    = {.ErrorNumber = 20,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E020,            .Title = ENG_Title_E020},
    [21]    = {.ErrorNumber = 21,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [22]    = {.ErrorNumber = 22,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,   .Description = ENG_Description_E022,            .Title = ENG_Title_E022},
    [23]    = {.ErrorNumber = 23,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E023,            .Title = ENG_Title_E023}, //REMOVED AT MBN
    [24]    = {.ErrorNumber = 24,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [25]    = {.ErrorNumber = 25,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [26]    = {.ErrorNumber = 26,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [27]    = {.ErrorNumber = 27,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [28]    = {.ErrorNumber = 28,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [29]    = {.ErrorNumber = 29,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [30]    = {.ErrorNumber = 30,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E030,            .Title = ENG_Title_E030},
    [31]    = {.ErrorNumber = 31,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E031,            .Title = ENG_Title_E031},
    [32]    = {.ErrorNumber = 32,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E032,            .Title = ENG_Title_E032},
    [33]    = {.ErrorNumber = 33,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E033,            .Title = ENG_Title_E033},
    [34]    = {.ErrorNumber = 34,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E034,            .Title = ENG_Title_E034},
    [35]    = {.ErrorNumber = 35,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E035,            .Title = ENG_Title_E035},
    [36]    = {.ErrorNumber = 36,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E036,            .Title = ENG_Title_E036},
    [37]    = {.ErrorNumber = 37,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E037,            .Title = ENG_Title_E037},
    [38]    = {.ErrorNumber = 38,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E038,            .Title = ENG_Title_E038},
    [39]    = {.ErrorNumber = 39,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E039,            .Title = ENG_Title_E039},
    [40]    = {.ErrorNumber = 40,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E040,            .Title = ENG_Title_E040},
    [41]    = {.ErrorNumber = 41,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E041,            .Title = ENG_Title_E041},
    [42]    = {.ErrorNumber = 42,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E042,            .Title = ENG_Title_E042},
    [43]    = {.ErrorNumber = 43,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E043,            .Title = ENG_Title_E043},
    [44]    = {.ErrorNumber = 44,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E044,            .Title = ENG_Title_E044},
    [45]    = {.ErrorNumber = 45,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E045,            .Title = ENG_Title_E045},
    [46]    = {.ErrorNumber = 46,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E046,            .Title = ENG_Title_E046},
    [47]    = {.ErrorNumber = 47,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E047,            .Title = ENG_Title_E047},
    [48]    = {.ErrorNumber = 48,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E048,            .Title = ENG_Title_E048},
    [49]    = {.ErrorNumber = 49,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [50]    = {.ErrorNumber = 50,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = KEEP,   .Description = ENG_Description_E050,            .Title = ENG_Title_E050},
    [51]    = {.ErrorNumber = 51,   .ErrorLevel = FL_WARNING,           .PopLevel = KEEP,   .Description = ENG_Description_E051,            .Title = ENG_Title_E051},
    [52]    = {.ErrorNumber = 52,   .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E052,            .Title = ENG_Title_E052},
    [53]    = {.ErrorNumber = 53,   .ErrorLevel = FL_WARNING,           .PopLevel = KEEP,   .Description = ENG_Description_E053,            .Title = ENG_Title_E053},
    [54]    = {.ErrorNumber = 54,   .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E054,            .Title = ENG_Title_E054},
    [55]    = {.ErrorNumber = 55,   .ErrorLevel = FL_WARNING,           .PopLevel = KEEP,   .Description = ENG_Description_E055,            .Title = ENG_Title_E055},
    [56]    = {.ErrorNumber = 56,   .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E056,            .Title = ENG_Title_E056},
    [57]    = {.ErrorNumber = 57,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,   .Description = ENG_Description_E057,            .Title = ENG_Title_E057},
    [58]    = {.ErrorNumber = 58,   .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,   .Description = ENG_Description_E058,            .Title = ENG_Title_E058},
    [59]    = {.ErrorNumber = 59,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,   .Description = ENG_Description_E059,            .Title = ENG_Title_E059},
    [60]    = {.ErrorNumber = 60,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E060,            .Title = ENG_Title_E060},
    [61]    = {.ErrorNumber = 61,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E061,            .Title = ENG_Title_E061},
    [62]    = {.ErrorNumber = 62,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,   .Description = ENG_Description_E062,            .Title = ENG_Title_E062},
    [63]    = {.ErrorNumber = 63,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [64]    = {.ErrorNumber = 64,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [65]    = {.ErrorNumber = 65,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [66]    = {.ErrorNumber = 66,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [67]    = {.ErrorNumber = 67,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [68]    = {.ErrorNumber = 68,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [69]    = {.ErrorNumber = 69,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [70]    = {.ErrorNumber = 70,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E070,            .Title = ENG_Title_E070},
    [71]    = {.ErrorNumber = 71,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E071,            .Title = ENG_Title_E071},
    [72]    = {.ErrorNumber = 72,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E072,            .Title = ENG_Title_E072},
    [73]    = {.ErrorNumber = 73,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E073,            .Title = ENG_Title_E073},
    [74]    = {.ErrorNumber = 74,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E074,            .Title = ENG_Title_E074},
    [75]    = {.ErrorNumber = 75,  .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,    .Description = ENG_Description_E075,            .Title = ENG_Title_E075},
    [76]    = {.ErrorNumber = 76,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [77]    = {.ErrorNumber = 77,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [78]    = {.ErrorNumber = 78,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [79]    = {.ErrorNumber = 79,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [80]    = {.ErrorNumber = 80,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [81]    = {.ErrorNumber = 81,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [82]    = {.ErrorNumber = 82,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [83]    = {.ErrorNumber = 83,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [84]    = {.ErrorNumber = 84,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [85]    = {.ErrorNumber = 85,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [86]    = {.ErrorNumber = 86,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [87]    = {.ErrorNumber = 87,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [88]    = {.ErrorNumber = 88,    .ErrorLevel = FL_WARNING,           .PopLevel = HIDE,  .Description = ENG_Description_E088,            .Title = ENG_Title_E088},
    [89]    = {.ErrorNumber = 89,                                                           .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [90]    = {.ErrorNumber = 90,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,  .Description = ENG_Description_E090,            .Title = ENG_Title_E090},
    [91]    = {.ErrorNumber = 91,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = KEEP,  .Description = ENG_Description_E091,            .Title = ENG_Title_E091},
    [92]    = {.ErrorNumber = 92,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E092,            .Title = ENG_Title_E092},
    [93]    = {.ErrorNumber = 93,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E093,            .Title = ENG_Title_E093},
    [94]    = {.ErrorNumber = 94,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E094,            .Title = ENG_Title_E094},
    [95]    = {.ErrorNumber = 95,    .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E095,            .Title = ENG_Title_E095},
    [96]    = {.ErrorNumber = 96,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E096,            .Title = ENG_Title_E096},
    [97]    = {.ErrorNumber = 97,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E097,            .Title = ENG_Title_E097},
    [98]    = {.ErrorNumber = 98,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E098,            .Title = ENG_Title_E098},
    [99]    = {.ErrorNumber = 99,    .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E099,            .Title = ENG_Title_E099},
    [100]   = {.ErrorNumber = 100,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [101]   = {.ErrorNumber = 101,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E101,            .Title = ENG_Title_E101},
    [102]   = {.ErrorNumber = 102,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E102,            .Title = ENG_Title_E102},
    [103]   = {.ErrorNumber = 103,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [104]   = {.ErrorNumber = 104,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [105]   = {.ErrorNumber = 105,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E105,            .Title = ENG_Title_E105},
    [106]   = {.ErrorNumber = 106,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [107]   = {.ErrorNumber = 107,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [108]   = {.ErrorNumber = 108,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [109]   = {.ErrorNumber = 109,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [110]   = {.ErrorNumber = 110,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [111]   = {.ErrorNumber = 111,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [112]   = {.ErrorNumber = 112,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [113]   = {.ErrorNumber = 113,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [114]   = {.ErrorNumber = 114,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [115]   = {.ErrorNumber = 115,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [116]   = {.ErrorNumber = 116,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [117]   = {.ErrorNumber = 117,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [118]   = {.ErrorNumber = 118,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [119]   = {.ErrorNumber = 119,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [120]   = {.ErrorNumber = 120,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = KEEP,  .Description = ENG_Description_E120,            .Title = ENG_Title_E120},
    [121]   = {.ErrorNumber = 121,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E121,            .Title = ENG_Title_E121},
    [122]   = {.ErrorNumber = 122,   .ErrorLevel = FL_WARNING,           .PopLevel = AUTO,  .Description = ENG_Description_E122,            .Title = ENG_Title_E122},
    [123]   = {.ErrorNumber = 123,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E123,            .Title = ENG_Title_E123},
    [124]   = {.ErrorNumber = 124,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E124,            .Title = ENG_Title_E124},
    [125]   = {.ErrorNumber = 125,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E125,            .Title = ENG_Title_E125},
    [126]   = {.ErrorNumber = 126,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E126,            .Title = ENG_Title_E126},
    [127]   = {.ErrorNumber = 127,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E127,            .Title = ENG_Title_E127},
    [128]   = {.ErrorNumber = 128,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [129]   = {.ErrorNumber = 129,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [130]   = {.ErrorNumber = 130,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E130,            .Title = ENG_Title_E130},
    [131]   = {.ErrorNumber = 131,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E131,            .Title = ENG_Title_E131},
    [132]   = {.ErrorNumber = 132,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E132,            .Title = ENG_Title_E132},
    [133]   = {.ErrorNumber = 133,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E133,            .Title = ENG_Title_E133},
    [134]   = {.ErrorNumber = 134,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [135]   = {.ErrorNumber = 135,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E135,            .Title = ENG_Title_E135},
    [136]   = {.ErrorNumber = 136,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E136,            .Title = ENG_Title_E136},
    [137]   = {.ErrorNumber = 137,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E137,            .Title = ENG_Title_E137},
    [138]   = {.ErrorNumber = 138,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E138,            .Title = ENG_Title_E138},
    [139]   = {.ErrorNumber = 139,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E139,            .Title = ENG_Title_E139},
    [140]   = {.ErrorNumber = 140,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E140,            .Title = ENG_Title_E140},
    [141]   = {.ErrorNumber = 141,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E141,            .Title = ENG_Title_E141},
    [142]   = {.ErrorNumber = 142,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E142,            .Title = ENG_Title_E142},
    [143]   = {.ErrorNumber = 143,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [144]   = {.ErrorNumber = 144,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [145]   = {.ErrorNumber = 145,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [146]   = {.ErrorNumber = 146,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [147]   = {.ErrorNumber = 147,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [148]   = {.ErrorNumber = 148,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [149]   = {.ErrorNumber = 149,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [150]   = {.ErrorNumber = 150,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E150,            .Title = ENG_Title_E150},
    [151]   = {.ErrorNumber = 151,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E151,            .Title = ENG_Title_E151},
    [152]   = {.ErrorNumber = 152,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E152,            .Title = ENG_Title_E152},
    [153]   = {.ErrorNumber = 153,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E153,            .Title = ENG_Title_E153},
    [154]   = {.ErrorNumber = 154,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E154,            .Title = ENG_Title_E154},
    [155]   = {.ErrorNumber = 155,   .ErrorLevel = FL_WARNING,           .PopLevel = HIDE,  .Description = ENG_Description_E155,            .Title = ENG_Title_E155},
    [156]   = {.ErrorNumber = 156,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [157]   = {.ErrorNumber = 157,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E157,            .Title = ENG_Title_E157},
    [158]   = {.ErrorNumber = 158,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [159]   = {.ErrorNumber = 159,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [160]   = {.ErrorNumber = 160,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [161]   = {.ErrorNumber = 161,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [162]   = {.ErrorNumber = 162,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [163]   = {.ErrorNumber = 163,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [164]   = {.ErrorNumber = 164,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [165]   = {.ErrorNumber = 165,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [166]   = {.ErrorNumber = 166,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [167]   = {.ErrorNumber = 167,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [168]   = {.ErrorNumber = 168,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [169]   = {.ErrorNumber = 169,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [170]   = {.ErrorNumber = 170,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [171]   = {.ErrorNumber = 171,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [172]   = {.ErrorNumber = 172,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [173]   = {.ErrorNumber = 173,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [174]   = {.ErrorNumber = 174,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [175]   = {.ErrorNumber = 175,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [176]   = {.ErrorNumber = 176,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [177]   = {.ErrorNumber = 177,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [178]   = {.ErrorNumber = 178,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [179]   = {.ErrorNumber = 179,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [180]   = {.ErrorNumber = 180,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [181]   = {.ErrorNumber = 181,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [182]   = {.ErrorNumber = 182,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [183]   = {.ErrorNumber = 183,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [184]   = {.ErrorNumber = 184,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [185]   = {.ErrorNumber = 185,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [186]   = {.ErrorNumber = 186,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [187]   = {.ErrorNumber = 187,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [188]   = {.ErrorNumber = 188,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [189]   = {.ErrorNumber = 189,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [190]   = {.ErrorNumber = 190,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [191]   = {.ErrorNumber = 191,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [192]   = {.ErrorNumber = 192,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [193]   = {.ErrorNumber = 193,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [194]   = {.ErrorNumber = 194,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [195]   = {.ErrorNumber = 195,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [196]   = {.ErrorNumber = 196,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [197]   = {.ErrorNumber = 197,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [198]   = {.ErrorNumber = 198,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [199]   = {.ErrorNumber = 199,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [200]   = {.ErrorNumber = 200,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E200,            .Title = ENG_Title_E200},
    [201]   = {.ErrorNumber = 201,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [202]   = {.ErrorNumber = 202,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E202,            .Title = ENG_Title_E202},
    [203]   = {.ErrorNumber = 203,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E203,            .Title = ENG_Title_E203},
    [204]   = {.ErrorNumber = 204,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E204,            .Title = ENG_Title_E204},
    [205]   = {.ErrorNumber = 205,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E205,            .Title = ENG_Title_E205},
    [206]   = {.ErrorNumber = 206,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E206,            .Title = ENG_Title_E206},
    [207]   = {.ErrorNumber = 207,   .ErrorLevel = FL_SIMPLE_FAILURE,    .PopLevel = AUTO,  .Description = ENG_Description_E207,            .Title = ENG_Title_E207},
    [208]   = {.ErrorNumber = 208,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [209]   = {.ErrorNumber = 209,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [210]   = {.ErrorNumber = 210,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [211]   = {.ErrorNumber = 211,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [212]   = {.ErrorNumber = 212,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [213]   = {.ErrorNumber = 213,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [214]   = {.ErrorNumber = 214,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [215]   = {.ErrorNumber = 215,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [216]   = {.ErrorNumber = 216,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [217]   = {.ErrorNumber = 217,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [218]   = {.ErrorNumber = 218,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [219]   = {.ErrorNumber = 219,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [220]   = {.ErrorNumber = 220,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E220,            .Title = ENG_Title_E220},
    [221]   = {.ErrorNumber = 221,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E221,            .Title = ENG_Title_E221},
    [222]   = {.ErrorNumber = 222,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E222,            .Title = ENG_Title_E222},
    [223]   = {.ErrorNumber = 223,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E223,            .Title = ENG_Title_E223},
    [224]   = {.ErrorNumber = 224,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [225]   = {.ErrorNumber = 225,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [226]   = {.ErrorNumber = 226,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [227]   = {.ErrorNumber = 227,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [228]   = {.ErrorNumber = 228,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [229]   = {.ErrorNumber = 229,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [230]   = {.ErrorNumber = 230,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [231]   = {.ErrorNumber = 231,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [232]   = {.ErrorNumber = 232,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [233]   = {.ErrorNumber = 233,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [234]   = {.ErrorNumber = 234,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [235]   = {.ErrorNumber = 235,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [236]   = {.ErrorNumber = 236,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [237]   = {.ErrorNumber = 237,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [238]   = {.ErrorNumber = 238,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [239]   = {.ErrorNumber = 239,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [240]   = {.ErrorNumber = 240,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E240,            .Title = ENG_Title_E240},
    [241]   = {.ErrorNumber = 241,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E241,            .Title = ENG_Title_E241},
    [242]   = {.ErrorNumber = 242,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E242,            .Title = ENG_Title_E242},
    [243]   = {.ErrorNumber = 243,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E243,            .Title = ENG_Title_E243},
    [244]   = {.ErrorNumber = 244,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E244,            .Title = ENG_Title_E244},
    [245]   = {.ErrorNumber = 245,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E245,            .Title = ENG_Title_E245},
    [246]   = {.ErrorNumber = 246,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E246,            .Title = ENG_Title_E246},
    [247]   = {.ErrorNumber = 247,   .ErrorLevel = FL_CRITICAL_FAILURE,  .PopLevel = AUTO,  .Description = ENG_Description_E247,            .Title = ENG_Title_E247},
    [248]   = {.ErrorNumber = 248,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [249]   = {.ErrorNumber = 249,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [250]   = {.ErrorNumber = 250,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [251]   = {.ErrorNumber = 251,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [252]   = {.ErrorNumber = 252,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [253]   = {.ErrorNumber = 253,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [254]   = {.ErrorNumber = 254,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
    [255]   = {.ErrorNumber = 255,                                                          .Description = ENG_Description_ErrorUnknown,    .Title = ENG_Title_ErrorUnknown},
};


//Error Container
unsigned char ActiveErrorNumber;
unsigned char LPSErrorBuffer[8];
Error_Variables ErrorFlags[256];

void Error_ClearAllMinimized()
{
    uint16_t i;
    for(i = 0; i < 256; i++) {
        ErrorFlags[i].Minimized = false;
    }
}

bool Error_CheckCleared()
{
    bool Cleared = false;
    if (ErrorList[ActiveErrorNumber].PopLevel == AUTO)
        if(!Error_CheckForErrorInBuf(ErrorList[ActiveErrorNumber].ErrorNumber))
            Cleared = true;
    return Cleared;
}
void Error_ClearPopup(bool RemoveLatch)
{
    if(RemoveLatch){           
        ErrorFlags[ActiveErrorNumber].Active = false;
        //Send Clear Latched Errors
        unsigned char Data[2]={0x60,0x60};
        SendMSG (&Data[0], sizeof(Data), UART_CTRL);
    }
    else{
        ErrorFlags[ActiveErrorNumber].Minimized = true;
    }     
}
void Error_ShowPopup()
{
    if(ActiveErrorNumber != 0)
    {
        //Clear Area
        ERC240_Display_EraseArea_Square(15,10,225,121);

        //Left Navigation text
        ERC240_Display_Character(16, 10, 5, (unsigned char*)Navigation49x21);
        ERC240_Display_String(41,10,ENG_Clear,0,'L',(unsigned char*)S6_Small_Fonts8x10);

        //Right Navigation text
        ERC240_Display_Character(175, 10, 4, (unsigned char *)Navigation49x21);
        ERC240_Display_String(175,10,ENG_Return,0,'L',(unsigned char *)S6_Small_Fonts8x10);

        //Frame
        ERC240_Display_XLine(15,9,210);
        ERC240_Display_XLine(15,121,210);
        ERC240_Display_XLine(16,122,209);
        ERC240_Display_YLine(15,10,111);
        ERC240_Display_YLine(224,10,111);
        ERC240_Display_YLine(225,11,111);

        //Title
        //ERC240_Display_String(120, 15, ErrorList[ActiveErrorNumber].Title, 0, 'C', (unsigned char *)S10B_Small_Fonts13x13);
        ERC240_Display_StringTextBox(120, 15, 100, ErrorList[ActiveErrorNumber].Title, (unsigned char *)S10B_Small_Fonts13x13, 0, 'C');

        //Description
        if(ErrorList[ActiveErrorNumber].Description == ENG_Description_ErrorUnknown){
            //Description
            ERC240_Display_String(120, 40, (unsigned char*)U8ToString(ActiveErrorNumber), 0, 'C', (unsigned char *)S18B_Helvetica24x29);
            ERC240_Display_String(120, 80, (unsigned char*)ErrorList[ActiveErrorNumber].Description, 0, 'C', (unsigned char *)S10_Small_Fonts12x13);
        }
        else   
            ERC240_Display_StringTextBox(120, 40, 200, ErrorList[ActiveErrorNumber].Description, (unsigned char *)S10_Small_Fonts12x13, 0, 'C');

        //Error Code
        ERC240_Display_String(20, 105, ENG_Error, 0, 'L', (unsigned char *)S10_Small_Fonts12x13);
        ERC240_Display_String(80, 105, (unsigned char*)U8ToString(ActiveErrorNumber), 0, 'L', (unsigned char *)S10_Small_Fonts12x13);

        //Error Level
        switch(ErrorList[ActiveErrorNumber].ErrorLevel){
            case FL_CRITICAL_FAILURE:
                ERC240_Display_String(220, 105, ENG_FL_Critical, 0, 'R', (unsigned char *)S10_Small_Fonts12x13);
                break;

            case FL_WARNING:
                ERC240_Display_String(220, 105, ENG_FL_Warning, 0, 'R', (unsigned char *)S10_Small_Fonts12x13);
                break;

            case FL_SIMPLE_FAILURE:
                ERC240_Display_String(220, 105, ENG_FL_Simple, 0, 'R', (unsigned char *)S10_Small_Fonts12x13);
                break;
        }
        
        //ERC240_Show_MemoryBuffer();
    }
}
bool Error_CheckForErrorInBuf(unsigned char Error)
{
    bool ErrorFound = false;
    if(Error > 0){
        unsigned char i;
        for(i = 0; i<8; i++){
            if(LPSErrorBuffer[i] == Error){
                ErrorFound = true;
                break;
            }
        }
    }
    return ErrorFound;
}        
bool Error_CheckForPopup()
{
    bool ErrorActive = false;
    unsigned char i;
    for (i = 0; i<8; i++)
    {
        if(ErrorFlags[LPSErrorBuffer[i]].Active)
        {
            //Error is only shown if it is not hidden or PopLevel is hidden
            if(!ErrorFlags[LPSErrorBuffer[i]].Minimized && (ErrorList[LPSErrorBuffer[i]].PopLevel != HIDE))
            {
                //Set active error
                ActiveErrorNumber = LPSErrorBuffer[i];
                ErrorActive = true;
                
                //Play sound if simple or critical error
                if((ErrorList[ActiveErrorNumber].ErrorLevel == FL_CRITICAL_FAILURE) || (ErrorList[ActiveErrorNumber].ErrorLevel == FL_SIMPLE_FAILURE)){
                    //Play Sound
                    if(Block_3_ID_3.NumValue & (1<<18)) //if sound enabled
                        BUZ_SetMelody(BUZ_ERROR);
                }
                break;
            }
        }
    }
    return ErrorActive;
}