"""Convert docs/SplashLogo.webp into main/splash_logo.c (LVGL 8 A8 image).

The logo is white on transparent; only the alpha channel is stored, and the
firmware recolors it (white) at draw time. Cropped to the visible logo and
scaled to WIDTH pixels.

Usage (from ClaytonDisplay/):  python tools/gen_splash.py
"""
from pathlib import Path
from PIL import Image

WIDTH = 560                      # 70 % of the 800 px panel
ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "SplashLogo.webp"
OUT = ROOT / "main" / "splash_logo.c"

alpha = Image.open(SRC).convert("RGBA").getchannel("A")
alpha = alpha.crop(alpha.getbbox())
h = round(alpha.height * WIDTH / alpha.width)
alpha = alpha.resize((WIDTH, h), Image.LANCZOS)
data = alpha.tobytes()

rows = []
for y in range(h):
    rows.append(", ".join(f"0x{b:02x}" for b in data[y * WIDTH:(y + 1) * WIDTH]))
body = ",\n".join(rows)

src = f"""/**
 * @file splash_logo.c
 * @brief Clayton Power splash logo as an LVGL A8 alpha image (recolorable).
 * Generated by tools/gen_splash.py from docs/SplashLogo.webp - do not edit.
 */
#include "lvgl.h"

static const uint8_t splash_logo_map[] = {{
{body}
}};

const lv_img_dsc_t splash_logo = {{
    .header = {{ .cf = LV_IMG_CF_ALPHA_8BIT, .always_zero = 0, .reserved = 0,
                 .w = {WIDTH}, .h = {h} }},
    .data_size = {WIDTH * h},
    .data = splash_logo_map,
}};
"""
OUT.write_text(src, newline="\n")
print(f"wrote {OUT} ({WIDTH}x{h}, {WIDTH * h} bytes)")
