export const ERROR_LEVEL = {
  WARNING: 'WARNING',
  FAILURE: 'FAILURE',
  CRITICAL: 'CRITICAL',
  UNKNOWN: 'UNKNOWN',
};

const ERROR_DEFINITIONS = [
  { code: 1, level: ERROR_LEVEL.CRITICAL, title: 'E001 EEPROM', description: 'Contact your retailer for support.' },
  { code: 2, level: ERROR_LEVEL.CRITICAL, title: 'E002 EEPROM', description: 'Contact your retailer for support.' },
  { code: 3, level: ERROR_LEVEL.CRITICAL, title: 'E003 High Voltage', description: 'Contact your retailer for support.' },
  { code: 4, level: ERROR_LEVEL.WARNING, title: 'E004 High Temp Warning', description: 'Unit is getting too hot. Allow it to cool down.' },
  { code: 5, level: ERROR_LEVEL.FAILURE, title: 'E005 High Temp Failure', description: 'Unit is too hot. Allow it to cool down.' },
  { code: 6, level: ERROR_LEVEL.WARNING, title: 'E006 Low Temp Warning', description: 'Unit is getting too cold. Allow it to warm up.' },
  { code: 7, level: ERROR_LEVEL.FAILURE, title: 'E007 Low Temp Failure', description: 'Unit is too cold. Allow it to warm up.' },
  { code: 8, level: ERROR_LEVEL.CRITICAL, title: 'E008 Broken Sensor', description: 'Contact your retailer for support.' },
  { code: 9, level: ERROR_LEVEL.CRITICAL, title: 'E009 Broken Sensor', description: 'Contact your retailer for support.' },
  { code: 10, level: ERROR_LEVEL.CRITICAL, title: 'E010 Efficiency', description: 'Contact your retailer for support.' },
  { code: 11, level: ERROR_LEVEL.FAILURE, title: 'E011 IO Overload', description: '12 VDC aux overloaded. Remove load to avoid shutdown.' },
  { code: 12, level: ERROR_LEVEL.FAILURE, title: 'E012 IO Overload', description: '12 VDC aux overloaded. Contact retailer.' },
  { code: 13, level: ERROR_LEVEL.FAILURE, title: 'E013 IO Overload', description: '12 VDC aux overloaded. Contact retailer.' },
  { code: 14, level: ERROR_LEVEL.FAILURE, title: 'E014 IO Overload', description: '12 VDC aux overloaded. Contact retailer.' },
  { code: 20, level: ERROR_LEVEL.FAILURE, title: 'E020 230 VAC Overload', description: '230 VAC overloaded. Remove load to avoid shutdown.' },
  { code: 22, level: ERROR_LEVEL.FAILURE, title: 'E022 Charger', description: 'Contact your retailer for support.' },
  { code: 23, level: ERROR_LEVEL.CRITICAL, title: 'E023 Charger', description: 'Contact your retailer for support.' },
  { code: 30, level: ERROR_LEVEL.CRITICAL, title: 'E030 Calibration', description: 'Contact your retailer for support.' },
  { code: 31, level: ERROR_LEVEL.CRITICAL, title: 'E031 Calibration', description: 'Contact your retailer for support.' },
  { code: 32, level: ERROR_LEVEL.CRITICAL, title: 'E032 Calibration', description: 'Contact your retailer for support.' },
  { code: 33, level: ERROR_LEVEL.CRITICAL, title: 'E033 Calibration', description: 'Contact your retailer for support.' },
  { code: 34, level: ERROR_LEVEL.CRITICAL, title: 'E034 Calibration', description: 'Contact your retailer for support.' },
  { code: 35, level: ERROR_LEVEL.CRITICAL, title: 'E035 Calibration', description: 'Contact your retailer for support.' },
  { code: 36, level: ERROR_LEVEL.CRITICAL, title: 'E036 Calibration', description: 'Contact your retailer for support.' },
  { code: 37, level: ERROR_LEVEL.CRITICAL, title: 'E037 Calibration', description: 'Contact your retailer for support.' },
  { code: 38, level: ERROR_LEVEL.CRITICAL, title: 'E038 Calibration', description: 'Contact your retailer for support.' },
  { code: 39, level: ERROR_LEVEL.CRITICAL, title: 'E039 Calibration', description: 'Contact your retailer for support.' },
  { code: 40, level: ERROR_LEVEL.CRITICAL, title: 'E040 Calibration', description: 'Contact your retailer for support.' },
  { code: 41, level: ERROR_LEVEL.CRITICAL, title: 'E041 Calibration', description: 'Contact your retailer for support.' },
  { code: 42, level: ERROR_LEVEL.CRITICAL, title: 'E042 Calibration', description: 'Contact your retailer for support.' },
  { code: 43, level: ERROR_LEVEL.CRITICAL, title: 'E043 Calibration', description: 'Contact your retailer for support.' },
  { code: 44, level: ERROR_LEVEL.CRITICAL, title: 'E044 Calibration', description: 'Contact your retailer for support.' },
  { code: 45, level: ERROR_LEVEL.CRITICAL, title: 'E045 Calibration', description: 'Contact your retailer for support.' },
  { code: 46, level: ERROR_LEVEL.CRITICAL, title: 'E046 Calibration', description: 'Contact your retailer for support.' },
  { code: 47, level: ERROR_LEVEL.CRITICAL, title: 'E047 Calibration', description: 'Contact your retailer for support.' },
  { code: 48, level: ERROR_LEVEL.CRITICAL, title: 'E048 Calibration', description: 'Contact your retailer for support.' },
  { code: 50, level: ERROR_LEVEL.CRITICAL, title: 'E050 Deep Discharge', description: 'Battery is deep-discharged. Contact retailer.' },
  { code: 51, level: ERROR_LEVEL.WARNING, title: 'E051 Battery Empty', description: 'Battery is empty. Charge the unit.' },
  { code: 52, level: ERROR_LEVEL.WARNING, title: 'E052 Battery Low', description: 'Battery is low. Charge the unit.' },
  { code: 53, level: ERROR_LEVEL.WARNING, title: 'E053 Battery Empty', description: 'Battery is empty. Charge the unit.' },
  { code: 54, level: ERROR_LEVEL.WARNING, title: 'E054 Cell Balancing', description: 'Cell balancing in progress. If warning remains after 24 hrs, contact retailer.' },
  { code: 55, level: ERROR_LEVEL.WARNING, title: 'E055 Cell Balancing', description: 'Cell balancing in progress. If failure remains after 24 hrs, contact retailer.' },
  { code: 56, level: ERROR_LEVEL.WARNING, title: 'E056 Low Temp Warning', description: 'Unit is getting too cold. Place in higher ambient temp.' },
  { code: 57, level: ERROR_LEVEL.FAILURE, title: 'E057 Low Temp Failure', description: 'Unit is too cold. Place in higher ambient temperature.' },
  { code: 58, level: ERROR_LEVEL.WARNING, title: 'E058 High Temp Warning', description: 'Unit is getting too hot. Place in lower ambient temp.' },
  { code: 59, level: ERROR_LEVEL.FAILURE, title: 'E059 High Temp Failure', description: 'Unit is too hot. Place in lower ambient temperature.' },
  { code: 60, level: ERROR_LEVEL.CRITICAL, title: 'E060 Battery Empty', description: 'Battery is empty. Charge the unit.' },
  { code: 61, level: ERROR_LEVEL.CRITICAL, title: 'E061 Battery Current', description: 'Discharge current too high. Remove 230 VAC and 12 VDC load.' },
  { code: 62, level: ERROR_LEVEL.CRITICAL, title: 'E062 Battery Current', description: 'Charge current too high. Disconnect all charge sources.' },
  { code: 70, level: ERROR_LEVEL.CRITICAL, title: 'E070 Solar Voltage', description: 'Check solar installation. Max 50 V from solar panel.' },
  { code: 71, level: ERROR_LEVEL.CRITICAL, title: 'E071 Solar Current', description: 'Check solar installation and max current from panel.' },
  { code: 72, level: ERROR_LEVEL.CRITICAL, title: 'E072 Solar', description: 'Contact your retailer for support.' },
  { code: 73, level: ERROR_LEVEL.CRITICAL, title: 'E073 Solar', description: 'Contact your retailer for support.' },
  { code: 74, level: ERROR_LEVEL.CRITICAL, title: 'E074 Solar', description: 'Contact your retailer for support.' },
  { code: 75, level: ERROR_LEVEL.CRITICAL, title: 'E075 Solar', description: 'Contact your retailer for support.' },
  { code: 88, level: ERROR_LEVEL.WARNING, title: 'E088 12 VDC Overload', description: '12 VDC Output overloaded. Remove load to avoid shutdown.' },
  { code: 90, level: ERROR_LEVEL.FAILURE, title: 'E090 DC Input Low', description: 'DC Input voltage too low. Check vehicle battery.' },
  { code: 91, level: ERROR_LEVEL.FAILURE, title: 'E091 DC Input High', description: 'DC Input voltage too high. Check vehicle battery.' },
  { code: 92, level: ERROR_LEVEL.FAILURE, title: 'E092 DC Input Overload', description: 'DC Input overloaded. Contact retailer.' },
  { code: 93, level: ERROR_LEVEL.FAILURE, title: 'E093 DC Input Failure', description: 'Unable to charge from vehicle. Check installation.' },
  { code: 94, level: ERROR_LEVEL.CRITICAL, title: 'E094 DC Input', description: 'Contact your retailer for support.' },
  { code: 95, level: ERROR_LEVEL.CRITICAL, title: 'E095 DC Input', description: 'Contact your retailer for support.' },
  { code: 96, level: ERROR_LEVEL.FAILURE, title: 'E096 DC Out Current', description: '12 VDC output charge current too high. Check installation.' },
  { code: 97, level: ERROR_LEVEL.FAILURE, title: 'E097 DC Out Failure', description: 'Remove 12 VDC load. Restart unit.' },
  { code: 101, level: ERROR_LEVEL.CRITICAL, title: 'E101 AC Offset', description: 'Contact your retailer for support.' },
  { code: 102, level: ERROR_LEVEL.CRITICAL, title: 'E102 DC Offset', description: 'Contact your retailer for support.' },
  { code: 105, level: ERROR_LEVEL.CRITICAL, title: 'E105 High Voltage', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 120, level: ERROR_LEVEL.CRITICAL, title: 'E120 DC Input Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 121, level: ERROR_LEVEL.FAILURE, title: 'E121 CAN Bus Failure', description: 'Check CAN cables. Contact retailer if failure remains.' },
  { code: 122, level: ERROR_LEVEL.WARNING, title: 'E122 Ext. High Temp', description: 'Extension getting too hot. Allow it to cool down.' },
  { code: 123, level: ERROR_LEVEL.FAILURE, title: 'E123 Ext. High Temp', description: 'Extension is too hot. Allow it to cool down.' },
  { code: 124, level: ERROR_LEVEL.FAILURE, title: 'E124 Ext. DC High', description: 'DC Input voltage too high. Check vehicle installation.' },
  { code: 125, level: ERROR_LEVEL.FAILURE, title: 'E125 Extension Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 126, level: ERROR_LEVEL.FAILURE, title: 'E126 Extension Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 127, level: ERROR_LEVEL.FAILURE, title: 'E127 Extension Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 130, level: ERROR_LEVEL.CRITICAL, title: 'E130 Power Supply', description: 'Contact your retailer for support.' },
  { code: 131, level: ERROR_LEVEL.CRITICAL, title: 'E131 Power Supply', description: 'Contact your retailer for support.' },
  { code: 132, level: ERROR_LEVEL.CRITICAL, title: 'E132 Power Supply', description: 'Contact your retailer for support.' },
  { code: 133, level: ERROR_LEVEL.CRITICAL, title: 'E133 Power Supply', description: 'Contact your retailer for support.' },
  { code: 135, level: ERROR_LEVEL.FAILURE, title: 'E135 Power Supply', description: 'Contact your retailer for support.' },
  { code: 136, level: ERROR_LEVEL.FAILURE, title: 'E136 Power Supply', description: 'Contact your retailer for support.' },
  { code: 137, level: ERROR_LEVEL.CRITICAL, title: 'E137 Power Supply', description: 'Contact your retailer for support.' },
  { code: 138, level: ERROR_LEVEL.FAILURE, title: 'E138 Power Supply', description: 'Contact your retailer for support.' },
  { code: 139, level: ERROR_LEVEL.FAILURE, title: 'E139 Power Supply', description: 'Contact your retailer for support.' },
  { code: 140, level: ERROR_LEVEL.FAILURE, title: 'E140 Power Supply', description: 'Contact your retailer for support.' },
  { code: 141, level: ERROR_LEVEL.FAILURE, title: 'E141 Power Supply', description: 'Contact your retailer for support.' },
  { code: 142, level: ERROR_LEVEL.FAILURE, title: 'E142 Power Supply', description: 'Contact your retailer for support.' },
  { code: 150, level: ERROR_LEVEL.FAILURE, title: 'E150 230 VAC Overload', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 151, level: ERROR_LEVEL.FAILURE, title: 'E151 230 VAC Overload', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 152, level: ERROR_LEVEL.FAILURE, title: 'E152 230 VAC Overload', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 153, level: ERROR_LEVEL.CRITICAL, title: 'E153 230 VAC Failure', description: 'Contact your retailer for support.' },
  { code: 154, level: ERROR_LEVEL.CRITICAL, title: 'E154 230 VAC Failure', description: 'Contact your retailer for support.' },
  { code: 155, level: ERROR_LEVEL.WARNING, title: 'E155 230 VAC Overload', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 157, level: ERROR_LEVEL.WARNING, title: 'E157 Inverter Cut-Off', description: 'Battery SOC below cut-off limit. Charge or decrease limit.' },
  { code: 200, level: ERROR_LEVEL.FAILURE, title: 'E200 AC Input Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 202, level: ERROR_LEVEL.FAILURE, title: 'E202 AC Input Failure', description: 'Restart unit. If failure remains, contact retailer.' },
  { code: 203, level: ERROR_LEVEL.FAILURE, title: 'E203 AC Input Failure', description: 'Remove 230 VAC load. Restart unit.' },
  { code: 204, level: ERROR_LEVEL.CRITICAL, title: 'E204 AC Input', description: 'Contact your retailer for support.' },
  { code: 205, level: ERROR_LEVEL.CRITICAL, title: 'E205 AC Input', description: 'Contact your retailer for support.' },
  { code: 206, level: ERROR_LEVEL.FAILURE, title: 'E206 AC In Voltage Low', description: '230 VAC IN voltage too low. Check supply/cables.' },
  { code: 207, level: ERROR_LEVEL.FAILURE, title: 'E207 AC In Voltage High', description: '230 VAC IN voltage too high. Check mains supply.' },
  { code: 220, level: ERROR_LEVEL.CRITICAL, title: 'E220 System AC', description: 'Contact your retailer for support.' },
  { code: 221, level: ERROR_LEVEL.CRITICAL, title: 'E221 System DC', description: 'Contact your retailer for support.' },
  { code: 222, level: ERROR_LEVEL.CRITICAL, title: 'E222 System', description: 'Contact your retailer for support.' },
  { code: 223, level: ERROR_LEVEL.CRITICAL, title: 'E223 Communication', description: 'Check CAN cables. Contact retailer if failure remains.' },
  { code: 240, level: ERROR_LEVEL.CRITICAL, title: 'E240 System Locked', description: 'Cell voltage critically low. Unit locked. Contact retailer.' },
  { code: 241, level: ERROR_LEVEL.CRITICAL, title: 'E241 System Locked', description: 'Cell voltage critically high. Unit locked. Contact retailer.' },
  { code: 242, level: ERROR_LEVEL.CRITICAL, title: 'E242 System Locked', description: 'Battery voltage critically low. Unit locked. Contact retailer.' },
  { code: 243, level: ERROR_LEVEL.CRITICAL, title: 'E243 System Locked', description: 'Battery voltage critically high. Unit locked. Contact retailer.' },
  { code: 244, level: ERROR_LEVEL.CRITICAL, title: 'E244 System Locked', description: 'Temperature critically low. Unit locked. Contact retailer.' },
  { code: 245, level: ERROR_LEVEL.CRITICAL, title: 'E245 System Locked', description: 'Temperature critically high. Unit locked. Contact retailer.' },
  { code: 246, level: ERROR_LEVEL.CRITICAL, title: 'E246 System Locked', description: 'Charge current critically high. Unit locked. Contact retailer.' },
  { code: 247, level: ERROR_LEVEL.CRITICAL, title: 'E247 System Locked', description: 'Discharge current critically high. Unit locked. Contact retailer.' },
];

const ERROR_BY_CODE = new Map(ERROR_DEFINITIONS.map((definition) => [definition.code, definition]));

export function getErrorDefinition(code) {
  const normalizedCode = Number(code) & 0xff;
  return ERROR_BY_CODE.get(normalizedCode) || {
    code: normalizedCode,
    level: ERROR_LEVEL.UNKNOWN,
    title: `E${String(normalizedCode).padStart(3, '0')} Unknown`,
    description: 'Contact your retailer for support.',
  };
}

export function activeErrorDefinitions(codes) {
  const seen = new Set();
  return (Array.isArray(codes) ? codes : [])
    .map((code) => Number(code) & 0xff)
    .filter((code) => {
      if (code === 0 || seen.has(code)) return false;
      seen.add(code);
      return true;
    })
    .map(getErrorDefinition);
}